use moltis_channels::store::StoredChannel;

pub(crate) fn render_people_md(channels: &[StoredChannel]) -> String {
    let mut out = String::new();
    out.push_str("# PEOPLE.md\n\n");
    out.push_str("_Auto-generated by Moltis from configured channels. Do not edit manually._\n\n");

    let mut telegram = Vec::new();
    for ch in channels {
        if ch.channel_type != "telegram" {
            continue;
        }
        telegram.push(ch);
    }

    if telegram.is_empty() {
        out.push_str("No channels configured.\n");
        return out;
    }

    out.push_str("## Telegram Bots\n\n");
    for ch in telegram {
        let cfg = &ch.config;
        let chan_user_id = cfg.get("chan_user_id").and_then(|v| v.as_u64());
        let chan_user_name = cfg.get("chan_user_name").and_then(|v| v.as_str());
        let chan_nickname = cfg.get("chan_nickname").and_then(|v| v.as_str());
        let persona_id = cfg.get("persona_id").and_then(|v| v.as_str());

        out.push_str(&format!("- account_id: `{}`\n", ch.account_id));
        if let Some(id) = chan_user_id {
            out.push_str(&format!("  - chan_user_id: `{}`\n", id));
        }
        if let Some(u) = chan_user_name {
            out.push_str(&format!("  - chan_user_name: `@{}`\n", u));
        }
        if let Some(n) = chan_nickname {
            out.push_str(&format!("  - chan_nickname: `{}`\n", n));
        }
        if let Some(p) = persona_id {
            out.push_str(&format!("  - persona_id: `{}`\n", p));
        }
    }
    out
}

pub(crate) fn regenerate_people_md(channels: &[StoredChannel]) -> anyhow::Result<()> {
    let path = moltis_config::people_path();
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let body = render_people_md(channels);
    std::fs::write(path, body)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn people_md_does_not_include_tokens() {
        let _guard = crate::test_support::TestDirsGuard::new();
        let channels = vec![StoredChannel {
            account_id: "telegram:123".into(),
            channel_type: "telegram".into(),
            config: serde_json::json!({
                "token": "123:SECRET",
                "chan_user_id": 123,
                "chan_user_name": "my_bot",
                "chan_nickname": "My Bot",
                "persona_id": "default",
            }),
            created_at: 0,
            updated_at: 0,
        }];

        let md = render_people_md(&channels);
        assert!(!md.contains("123:SECRET"), "must not leak token");
        assert!(md.contains("telegram:123"));
        assert!(md.contains("@my_bot"));
        assert!(md.contains("persona_id"));

        regenerate_people_md(&channels).expect("write people");
        let saved = std::fs::read_to_string(moltis_config::people_path()).expect("read file");
        assert!(!saved.contains("123:SECRET"), "must not leak token");
    }
}
